### ISSUE TITLE
Set up CI for our project

### ISSUE THREAD

**Issue by cdeler** [cdeler/woogle#27]
As we have a couple of unit tests, we should set up CI with github integration.

Acceptance criteria:
1. [x] all pull request to the `master` branch are followed by unit tests execution
1. [x] the unit test execution should be integrated with github
1. [x] the unit test status indicator shold be added to the readme

**Comment by klimente** [comment]
1.2.Need to add https://github.com/klimente/woogle/blob/master/.travis.yml and https://github.com/klimente/woogle/blob/master/requirements.txt  this files in root directory, then go to travis-ci.org and add our project in admin account. 
3. Click on status image, and choose markdown in second selectbox , then copy provided string and past this into README.md
